import {getFirestore,doc,getDoc,setDoc,collection,getDocs,serverTimestamp}from'firebase/firestore';import{auth}from'./firebaseConfig';import AsyncStorage from'@react-native-async-storage/async-storage';const db=getFirestore();
export function getWeekKey(){const now=new Date();const year=now.getFullYear();const d1=new Date(year,0,1);const week=Math.ceil(((now.getTime()-d1.getTime())/86400000+d1.getDay()+1)/7);return`${year}_W${String(week).padStart(2,'0')}`}
export function getDayKey(){const d=new Date();return d.toISOString().slice(0,10)}
export interface ScoreArena{uid:string;prenom:string;classe?:string;score:number;points:number;pointsSemaine?:number;moyenneHebdo?:number;joursJoues?:number;eligibleRecompense?:boolean;matiere:string;tempsMs:number;date:string;weekKey:string;dayKey?:string;dailyScores?:Record<string,{score:number;points:number;tempsMs:number;matiere:string;date:string}>}
export async function sauvegarderScoreArena(score:ScoreArena):Promise<void>{try{const user=auth.currentUser;if(!user)return;const wk=score.weekKey||getWeekKey();const day=score.dayKey||getDayKey();const ref=doc(db,'rankings',wk,'scores',user.uid);const existing=await getDoc(ref);const old=existing.exists()?existing.data() as ScoreArena:null;const daily={...(old?.dailyScores||{})};const current=daily[day];if(current&&current.score>=score.score)return;daily[day]={score:score.score,points:score.score,tempsMs:score.tempsMs,matiere:score.matiere,date:score.date};const entries=Object.values(daily);const totalPoints=entries.reduce((a,b)=>a+b.points,0);const moyenne=entries.length?entries.reduce((a,b)=>a+b.score,0)/entries.length:0;const data={uid:user.uid,prenom:(user.displayName||score.prenom||'Élève'),classe:score.classe||'',score:score.score,points:score.points,pointsSemaine:totalPoints,moyenneHebdo:Math.round(moyenne*10)/10,joursJoues:entries.length,eligibleRecompense:entries.length>=3&&moyenne>13,matiere:score.matiere,tempsMs:score.tempsMs,date:score.date,weekKey:wk,dayKey:day,dailyScores:daily,updatedAt:serverTimestamp()};await setDoc(ref,data,{merge:true});await AsyncStorage.setItem(`arena_score_${wk}`,JSON.stringify(data));await AsyncStorage.setItem(`arena_day_${day}`,'played')}catch(e){console.error('Erreur sauvegarde score arena:',e)}}
export async function aDejaJoueAujourdHui(){return(await AsyncStorage.getItem(`arena_day_${getDayKey()}`))==='played'}
export async function getClassementSemaine(weekKey?:string,classe?:string):Promise<ScoreArena[]>{try{const wk=weekKey||getWeekKey();const snap=await getDocs(collection(db,'rankings',wk,'scores'));return snap.docs.map(d=>d.data() as ScoreArena).filter(s=>!classe||!s.classe||s.classe===classe).sort((a,b)=>(b.pointsSemaine??b.points)-(a.pointsSemaine??a.points)||(b.moyenneHebdo??b.score)-(a.moyenneHebdo??a.score)).slice(0,50)}catch(e){console.error('Erreur classement:',e);return[]}}
export async function getMonMeilleurScore(weekKey?:string):Promise<ScoreArena|null>{try{const user=auth.currentUser;if(!user)return null;const ref=doc(db,'rankings',weekKey||getWeekKey(),'scores',user.uid);const snap=await getDoc(ref);return snap.exists()?snap.data() as ScoreArena:null}catch{return null}}
export async function getHistoriqueDuels():Promise<ScoreArena[]>{try{const val=await AsyncStorage.getItem('arena_historique');return val?JSON.parse(val):[]}catch{return[]}}
export async function ajouterAuHistorique(score:ScoreArena){try{const hist=await getHistoriqueDuels();await AsyncStorage.setItem('arena_historique',JSON.stringify([score,...hist].slice(0,20)))}catch{}}
export function scoreKeba(matiere:string){const bases:Record<string,number>={maths:16,svt:15,francais:14,physique:15,histgeo:14,philo:13,anglais:14,info:15};const base=bases[matiere.toLowerCase()]||14;return Math.min(20,Math.max(8,base+Math.floor(Math.random()*5)-2))}
