import React, { useCallback, useState } from 'react';
import { View, Text, StyleSheet, FlatList, TouchableOpacity, ActivityIndicator } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useTheme } from '../../context/ThemeContext';
import { auth, db } from '../../services/firebaseConfig';
import { Reservation } from '../../services/tuteurService';
import { collection, getDocs, query, where, orderBy } from 'firebase/firestore';

const STATUTS:any={en_attente:{label:'En attente',icon:'clock-outline'},confirmee:{label:'Confirmée',icon:'check-circle-outline'},terminee:{label:'Terminée',icon:'check-all'},annulee:{label:'Annulée',icon:'close-circle-outline'}};
export default function MesReservationsParentScreen({navigation}:any){
 const {colors}=useTheme(); const [reservations,setReservations]=useState<Reservation[]>([]); const [loading,setLoading]=useState(true); const [filtre,setFiltre]=useState<any>('toutes');
 const charger=useCallback(async()=>{setLoading(true);try{const user=auth.currentUser;if(!user){setReservations([]);return;}try{const s=await getDocs(query(collection(db,'reservations'),where('eleveId','==',user.uid),orderBy('dateCreation','desc')));setReservations(s.docs.map(d=>({id:d.id,...d.data()})) as Reservation[]);}catch{const s=await getDocs(query(collection(db,'reservations'),where('eleveId','==',user.uid)));setReservations(s.docs.map(d=>({id:d.id,...d.data()})) as Reservation[]);}}catch(e){console.error(e);setReservations([]);}finally{setLoading(false);}},[]);
 useFocusEffect(useCallback(()=>{charger();},[charger]));
 const liste=filtre==='toutes'?reservations:reservations.filter(r=>r.statut===filtre);
 const trouver=()=>navigation.getParent()?.navigate('TousRepetiteursScreen');
 if(loading)return <View style={[styles.center,{backgroundColor:colors.background}]}><ActivityIndicator size="large" color={colors.primary}/><Text style={{color:colors.textMuted,marginTop:10}}>Chargement de vos réservations…</Text></View>;
 return <View style={[styles.container,{backgroundColor:colors.background}]}>
  <View style={[styles.header,{backgroundColor:colors.surface,borderBottomColor:colors.border}]}><View><Text style={[styles.title,{color:colors.text}]}>Mes réservations</Text><Text style={[styles.subtitle,{color:colors.textMuted}]}>Suivez les cours de votre enfant</Text></View><TouchableOpacity onPress={charger} style={[styles.refresh,{backgroundColor:colors.primary+'15'}]}><MaterialCommunityIcons name="refresh" size={21} color={colors.primary}/></TouchableOpacity></View>
  <FlatList horizontal data={[{key:'toutes',label:'Toutes'},{key:'en_attente',label:'En attente'},{key:'confirmee',label:'Confirmées'},{key:'terminee',label:'Terminées'},{key:'annulee',label:'Annulées'}]} keyExtractor={x=>x.key} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters} renderItem={({item})=><TouchableOpacity onPress={()=>setFiltre(item.key)} style={[styles.filter,{backgroundColor:filtre===item.key?colors.primary:colors.surface,borderColor:filtre===item.key?colors.primary:colors.border}]}><Text style={{color:filtre===item.key?'white':colors.textSecondary,fontSize:12,fontWeight:'700'}}>{item.label}</Text></TouchableOpacity>}/>
  <FlatList data={liste} keyExtractor={(x,index)=>x.id || String(index)} contentContainerStyle={styles.list} renderItem={({item})=>{const st=STATUTS[item.statut]||STATUTS.en_attente;return <TouchableOpacity onPress={()=>navigation.getParent()?.navigate('ParentRepetiteurDetail',{tuteurId:item.tuteurId})} style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={styles.top}><View style={[styles.avatar,{backgroundColor:colors.primary+'15'}]}><MaterialCommunityIcons name="account-school-outline" size={25} color={colors.primary}/></View><View style={{flex:1}}><Text style={[styles.name,{color:colors.text}]}>{item.tuteurNom||'Répétiteur'}</Text><Text style={{color:colors.textSecondary,fontSize:12}}>{item.matiere}</Text></View><View style={[styles.badge,{backgroundColor:colors.primary+'15'}]}><MaterialCommunityIcons name={st.icon} size={14} color={colors.primary}/><Text style={{color:colors.primary,fontSize:10,fontWeight:'800'}}>{st.label}</Text></View></View><View style={styles.info}><Text style={{color:colors.textMuted,fontSize:11}}>📅 {item.date||'Date à confirmer'}</Text><Text style={{color:colors.textMuted,fontSize:11}}>🕐 {item.heure||'Heure à confirmer'}</Text><Text style={{color:colors.textMuted,fontSize:11}}>{item.dureeMin||0} min</Text></View><View style={styles.footer}><Text style={{color:colors.primary,fontWeight:'800',fontSize:12}}>Voir le répétiteur</Text><MaterialCommunityIcons name="chevron-right" size={20} color={colors.primary}/></View></TouchableOpacity>}} ListEmptyComponent={<View style={styles.empty}><MaterialCommunityIcons name="calendar-search" size={58} color={colors.textMuted}/><Text style={[styles.emptyTitle,{color:colors.text}]}>Aucune réservation</Text><Text style={[styles.emptyText,{color:colors.textMuted}]}>Trouvez un répétiteur pour commencer.</Text><TouchableOpacity onPress={trouver} style={[styles.cta,{backgroundColor:colors.primary}]}><MaterialCommunityIcons name="account-search" size={20} color="white"/><Text style={styles.ctaText}>Trouver un répétiteur</Text></TouchableOpacity></View>}/>
 </View>;
}
const styles=StyleSheet.create({container:{flex:1},center:{flex:1,alignItems:'center',justifyContent:'center'},header:{padding:18,borderBottomWidth:1,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{fontSize:22,fontWeight:'900'},subtitle:{fontSize:12,marginTop:3},refresh:{width:42,height:42,borderRadius:21,alignItems:'center',justifyContent:'center'},filters:{padding:12,gap:8},filter:{borderWidth:1,borderRadius:20,paddingHorizontal:13,paddingVertical:8},list:{padding:14,gap:12,paddingBottom:30},card:{borderWidth:1,borderRadius:18,padding:15},top:{flexDirection:'row',alignItems:'center',gap:10},avatar:{width:48,height:48,borderRadius:24,alignItems:'center',justifyContent:'center'},name:{fontSize:16,fontWeight:'800'},badge:{flexDirection:'row',alignItems:'center',gap:4,paddingHorizontal:8,paddingVertical:6,borderRadius:12},info:{flexDirection:'row',flexWrap:'wrap',gap:12,marginTop:14},footer:{marginTop:14,paddingTop:11,borderTopWidth:1,borderTopColor:'#00000010',flexDirection:'row',justifyContent:'space-between',alignItems:'center'},empty:{alignItems:'center',padding:50,gap:9},emptyTitle:{fontSize:19,fontWeight:'900'},emptyText:{fontSize:13,textAlign:'center'},cta:{marginTop:10,minHeight:48,paddingHorizontal:18,borderRadius:14,flexDirection:'row',alignItems:'center',gap:7},ctaText:{color:'white',fontWeight:'900'}});
