import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, ActivityIndicator, Image } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useTheme } from '../../context/ThemeContext';
import { getTuteur, Tuteur } from '../../services/tuteurService';
import { db } from '../../services/firebaseConfig';
import { collection, getDocs, query, where } from 'firebase/firestore';

export default function ParentRepetiteurDetailScreen({ route, navigation }: any) {
  const { colors }=useTheme(); const [tuteur,setTuteur]=useState<Tuteur|null>(route?.params?.tuteur||null); const [loading,setLoading]=useState(!tuteur); const [coursEnLigne,setCoursEnLigne]=useState(0); const id=route?.params?.tuteurId||route?.params?.tuteur?.uid;
  useEffect(()=>{if(!id)return;(async()=>{setLoading(!tuteur);try{const [profil,cours]=await Promise.all([getTuteur(id),getDocs(query(collection(db,'contributions'),where('auteur.userId','==',id),where('statut','==','validé')))]);if(profil)setTuteur(prev=>({...prev,...profil}));setCoursEnLigne(cours.size);}catch(e){console.error(e);}finally{setLoading(false);}})();},[id]);
  if(loading)return <View style={[styles.center,{backgroundColor:colors.background}]}><ActivityIndicator size="large" color={colors.primary}/></View>;
  if(!tuteur)return <View style={[styles.center,{backgroundColor:colors.background}]}><Text style={{color:colors.text}}>Profil introuvable.</Text><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={{color:colors.primary,marginTop:10}}>Retour</Text></TouchableOpacity></View>;
  return <ScrollView style={[styles.container,{backgroundColor:colors.background}]} contentContainerStyle={styles.content}>
    <View style={[styles.profile,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={[styles.avatar,{backgroundColor:colors.primary+'15'}]}>{tuteur.profileImage?<Image source={{uri:tuteur.profileImage}} style={styles.avatarImage}/>:<Text style={styles.avatarText}>👨🏾‍🏫</Text>}</View><Text style={[styles.name,{color:colors.text}]}>{tuteur.prenom} {tuteur.nom}</Text>{tuteur.statut==='certifie'&&<View style={[styles.badge,{backgroundColor:colors.primary+'18'}]}><MaterialCommunityIcons name="check-decagram" size={16} color={colors.primary}/><Text style={{color:colors.primary,fontWeight:'800'}}>Certifié RÉPÉTIA</Text></View>}<View style={styles.rating}><MaterialCommunityIcons name="star" size={19} color={colors.warning}/><Text style={[styles.ratingText,{color:colors.text}]}>{Number(tuteur.noteGlobale||0).toFixed(1)} · {tuteur.nbAvis||0} avis</Text></View><Text style={[styles.meta,{color:colors.textMuted}]}>{tuteur.disponible?'● Disponible':'● Indisponible'} · {tuteur.universite||'Gabon'}</Text></View>
    <View style={[styles.stats,{backgroundColor:colors.surface,borderColor:colors.border}]}>{[[coursEnLigne,'Cours en ligne'],[tuteur.nbSessions||0,'Sessions'],[tuteur.nbAvis||0,'Avis'],[tuteur.anneeExp||0,'Ans exp.']].map(([v,l])=><View key={String(l)} style={styles.stat}><Text style={[styles.value,{color:colors.primary}]}>{v}</Text><Text style={[styles.label,{color:colors.textMuted}]}>{l}</Text></View>)}</View>
    <View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.title,{color:colors.text}]}>À propos</Text><Text style={[styles.body,{color:colors.textSecondary}]}>{tuteur.bio||'Présentation non renseignée.'}</Text></View>
    <View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.title,{color:colors.text}]}>Matières</Text><View style={styles.wrap}>{(tuteur.matieres||[]).map(m=><View key={m} style={[styles.chip,{backgroundColor:colors.primary+'15'}]}><Text style={{color:colors.primary,fontWeight:'700',fontSize:12}}>{m}</Text></View>)}</View></View>
    <View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.title,{color:colors.text}]}>Tarifs</Text>{[['30 min',tuteur.prix30min],['1 heure',tuteur.prix60min],['Mensuel',tuteur.prixMensuel]].map(([l,p])=><View key={String(l)} style={styles.priceRow}><Text style={[styles.body,{color:colors.textSecondary}]}>{l}</Text><Text style={[styles.price,{color:colors.primary}]}>{Number(p||0).toLocaleString()} FCFA</Text></View>)}</View>
    <TouchableOpacity onPress={()=>navigation.navigate('ParentReservation',{tuteurId:tuteur.uid,tuteur})} style={[styles.cta,{backgroundColor:colors.primary}]}><MaterialCommunityIcons name="calendar-check" size={21} color="white"/><Text style={styles.ctaText}>Réserver un cours</Text></TouchableOpacity>
  </ScrollView>;
}
const styles=StyleSheet.create({container:{flex:1},content:{padding:16,paddingBottom:35},profile:{borderWidth:1,borderRadius:20,padding:20,alignItems:'center'},avatar:{width:78,height:78,borderRadius:39,alignItems:'center',justifyContent:'center',overflow:'hidden'},avatarImage:{width:'100%',height:'100%'},avatarText:{fontSize:38},name:{fontSize:23,fontWeight:'900',marginTop:10},badge:{marginTop:7,paddingHorizontal:10,paddingVertical:6,borderRadius:12,flexDirection:'row',alignItems:'center',gap:5},rating:{flexDirection:'row',alignItems:'center',gap:5,marginTop:8},ratingText:{fontSize:13,fontWeight:'800'},meta:{fontSize:11,marginTop:7},stats:{borderWidth:1,borderRadius:17,flexDirection:'row',paddingVertical:15,marginTop:12},stat:{flex:1,alignItems:'center'},value:{fontSize:20,fontWeight:'900'},label:{fontSize:10,marginTop:3},card:{borderWidth:1,borderRadius:17,padding:15,marginTop:12},title:{fontSize:16,fontWeight:'900',marginBottom:9},body:{fontSize:13,lineHeight:19},wrap:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{paddingHorizontal:10,paddingVertical:8,borderRadius:12},priceRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:8},price:{fontSize:14,fontWeight:'900'},cta:{minHeight:52,borderRadius:15,marginTop:16,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8},ctaText:{color:'white',fontSize:15,fontWeight:'900'},center:{flex:1,alignItems:'center',justifyContent:'center'}});
