import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, TextInput, Alert } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useTheme } from '../../context/ThemeContext';
import { useAuth } from '../../context/AuthContext';
import { auth, db } from '../../services/firebaseConfig';
import { doc, updateDoc } from 'firebase/firestore';
import { sendPasswordResetEmail } from 'firebase/auth';

export default function ParentCompteScreen({route,navigation}:any){const{colors}=useTheme();const{userData}=useAuth();const parent:any=userData||{};const mode=route?.params?.mode||'personal';const[prenom,setPrenom]=useState(String(parent.prenom||''));const[nom,setNom]=useState(String(parent.nom||''));const[telephone,setTelephone]=useState(String(parent.telephone||''));const[saving,setSaving]=useState(false);const[notifications,setNotifications]=useState(true);
 const save=async()=>{if(!auth.currentUser)return;setSaving(true);try{await updateDoc(doc(db,'users',auth.currentUser.uid),{prenom:prenom.trim(),nom:nom.trim(),telephone:telephone.trim()});Alert.alert('Enregistré','Vos informations ont été mises à jour.');navigation.goBack()}catch(e){Alert.alert('Erreur','Impossible de mettre à jour le profil.')}finally{setSaving(false)}};
 const security=async()=>{if(!auth.currentUser?.email)return;try{await sendPasswordResetEmail(auth,auth.currentUser.email);Alert.alert('Email envoyé','Un lien de réinitialisation du mot de passe a été envoyé à votre adresse.')}catch{Alert.alert('Erreur','Impossible d’envoyer le lien.')}};
 return <ScrollView style={[styles.container,{backgroundColor:colors.background}]} contentContainerStyle={styles.content}><Text style={[styles.title,{color:colors.text}]}>{mode==='security'?'Sécurité':mode==='notifications'?'Notifications':'Informations personnelles'}</Text>{mode==='personal'?<View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><Field label="Prénom" value={prenom} onChange={setPrenom} colors={colors}/><Field label="Nom" value={nom} onChange={setNom} colors={colors}/><Field label="Téléphone" value={telephone} onChange={setTelephone} colors={colors} keyboard="phone-pad"/><Text style={[styles.helper,{color:colors.textMuted}]}>Email : {auth.currentUser?.email||parent.email||'—'}</Text><TouchableOpacity style={[styles.button,{backgroundColor:colors.primary}]} disabled={saving} onPress={save}><MaterialCommunityIcons name="content-save-outline" size={20} color="#fff"/><Text style={styles.buttonText}>{saving?'Enregistrement…':'Enregistrer'}</Text></TouchableOpacity></View>:mode==='security'?<View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><MaterialCommunityIcons name="shield-lock-outline" size={34} color={colors.primary}/><Text style={[styles.cardTitle,{color:colors.text}]}>Mot de passe</Text><Text style={[styles.helper,{color:colors.textMuted}]}>Votre mot de passe est géré par Firebase. Nous ne le stockons jamais dans RÉPETIA.</Text><TouchableOpacity style={[styles.button,{backgroundColor:colors.primary}]} onPress={security}><Text style={styles.buttonText}>Réinitialiser mon mot de passe</Text></TouchableOpacity></View>:<View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.cardTitle,{color:colors.text}]}>Préférences de notification</Text><TouchableOpacity style={styles.toggleRow} onPress={()=>setNotifications(v=>!v)}><View style={{flex:1}}><Text style={[styles.cardTitle,{color:colors.text,fontSize:14}]}>Alertes importantes</Text><Text style={[styles.helper,{color:colors.textMuted}]}>Nouveaux rapports, réservations et alertes de suivi.</Text></View><MaterialCommunityIcons name={notifications?'toggle-switch':'toggle-switch-off-outline'} size={42} color={notifications?colors.primary:colors.textMuted}/></TouchableOpacity></View>}</ScrollView>}
function Field({label,value,onChange,colors,keyboard}:any){return <View style={{marginBottom:13}}><Text style={[styles.label,{color:colors.text}]}>{label}</Text><TextInput value={value} onChangeText={onChange} keyboardType={keyboard||'default'} placeholder={label} placeholderTextColor={colors.textMuted} style={[styles.input,{backgroundColor:colors.background,borderColor:colors.border,color:colors.text}]}/></View>}
const styles=StyleSheet.create({container:{flex:1},content:{padding:16},title:{fontSize:25,fontWeight:'900',marginBottom:14},card:{borderWidth:1,borderRadius:20,padding:16},label:{fontSize:12,fontWeight:'800',marginBottom:6},input:{minHeight:48,borderWidth:1,borderRadius:13,paddingHorizontal:12,fontSize:14},helper:{fontSize:12,lineHeight:18,marginTop:5},button:{minHeight:50,borderRadius:15,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,marginTop:16},buttonText:{color:'#fff',fontSize:13,fontWeight:'900'},cardTitle:{fontSize:16,fontWeight:'900',marginTop:10},toggleRow:{flexDirection:'row',alignItems:'center',marginTop:18}});
