import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, TextInput, Alert, Linking } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useTheme } from '../../context/ThemeContext';

export default function ParentSupport() {
  const { colors } = useTheme(); const [message,setMessage]=useState('');
  const envoyer=()=>{if(!message.trim()){Alert.alert('Message requis','Décrivez votre besoin avant d’envoyer votre demande.');return;}Alert.alert('Demande prête','Votre demande a été préparée. Connectez le support RÉPETIA pour finaliser l’envoi.');};
  return <ScrollView style={[styles.container,{backgroundColor:colors.background}]} contentContainerStyle={styles.content}>
    <View style={[styles.hero,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={[styles.icon,{backgroundColor:colors.primary+'18'}]}><MaterialCommunityIcons name="lifebuoy" size={28} color={colors.primary}/></View><Text style={[styles.title,{color:colors.text}]}>Aide & support</Text><Text style={[styles.body,{color:colors.textSecondary}]}>Une question sur votre compte, un enfant, une réservation ou votre abonnement ? RÉPETIA est là pour vous aider.</Text></View>
    <Text style={[styles.section,{color:colors.text}]}>Nous contacter</Text><TouchableOpacity style={[styles.contact,{backgroundColor:colors.surface,borderColor:colors.border}]} onPress={()=>Linking.openURL('mailto:support@repetia.app')}><MaterialCommunityIcons name="email-outline" size={23} color={colors.primary}/><View style={{flex:1}}><Text style={[styles.label,{color:colors.text}]}>Email support</Text><Text style={[styles.body,{color:colors.textMuted}]}>support@repetia.app</Text></View><MaterialCommunityIcons name="chevron-right" size={20} color={colors.textMuted}/></TouchableOpacity>
    <View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.label,{color:colors.text}]}>Votre message</Text><TextInput value={message} onChangeText={setMessage} multiline numberOfLines={6} textAlignVertical="top" placeholder="Décrivez votre problème ou votre question…" placeholderTextColor={colors.textMuted} style={[styles.input,{backgroundColor:colors.background,borderColor:colors.border,color:colors.text}]}/><TouchableOpacity style={[styles.button,{backgroundColor:colors.primary}]} onPress={envoyer}><MaterialCommunityIcons name="send-outline" size={20} color="#fff"/><Text style={styles.buttonText}>Envoyer au support</Text></TouchableOpacity></View>
  </ScrollView>;
}
const styles=StyleSheet.create({container:{flex:1},content:{padding:16,paddingBottom:34,gap:12},hero:{borderWidth:1,borderRadius:22,padding:18},icon:{width:54,height:54,borderRadius:17,justifyContent:'center',alignItems:'center',marginBottom:12},title:{fontSize:24,fontWeight:'900'},body:{fontSize:12,lineHeight:19,marginTop:5},section:{fontSize:17,fontWeight:'900',marginTop:4},contact:{borderWidth:1,borderRadius:18,padding:15,flexDirection:'row',alignItems:'center',gap:12},label:{fontSize:13,fontWeight:'900'},card:{borderWidth:1,borderRadius:18,padding:15},input:{minHeight:130,borderWidth:1,borderRadius:14,padding:12,marginTop:9,fontSize:13},button:{minHeight:50,borderRadius:15,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,marginTop:12},buttonText:{color:'#fff',fontSize:13,fontWeight:'900'}});
