import React, { useCallback, useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView, ActivityIndicator, Alert, Linking } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useFocusEffect } from '@react-navigation/native';
import { useTheme } from '../../context/ThemeContext';
import { useAuth } from '../../context/AuthContext';
import { getEnfantsLies, EnfantLie } from '../../services/parentService';
const WHATSAPP_NUMBER='24160217098';
const PLANS=[{name:'FREE',price:'0 FCFA',desc:'Pour découvrir RÉPETIA',features:['Suivi essentiel','1 élève']},{name:'GOLD',price:'5 000 FCFA/mois',desc:'Pour un accompagnement régulier',features:['Suivi avancé','Analyses et recommandations','Jusqu’à 5 élèves']},{name:'PLATINIUM',price:'18 000 FCFA/mois',desc:'Pour une famille très accompagnée',features:['Tout GOLD','Suivi approfondi','Priorité support','Jusqu’à 5 élèves']}];
export default function ParentParametres({navigation}:any){const{colors}=useTheme();const{userData,logout}=useAuth();const parent:any=userData||{};const nom=[parent.prenom,parent.nom].filter(Boolean).join(' ')||'Parent';const[enfants,setEnfants]=useState<EnfantLie[]>([]);const[loading,setLoading]=useState(true);const charger=useCallback(async()=>{setLoading(true);try{setEnfants(await getEnfantsLies())}finally{setLoading(false)}},[]);useFocusEffect(useCallback(()=>{charger()},[charger]));
 const deconnecter=()=>Alert.alert('Déconnexion','Voulez-vous vous déconnecter ?', [{text:'Annuler',style:'cancel'},{text:'Déconnexion',style:'destructive',onPress:logout}]);
 const choisirPlan=(p:any)=>{if(p.name==='FREE'){Alert.alert('Plan FREE','Le plan Free est actif sans paiement.');return}const message=`Bonjour ! Je souhaite activer le plan ${p.name} de RÉPETIA.\n\nPlan : ${p.name}\nPrix : ${p.price}\nEmail : ${parent.email||'non renseigné'}\n\nJe souhaite connaître la procédure de paiement et d’activation.`;Linking.openURL(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`).catch(()=>Alert.alert('WhatsApp indisponible',`Contactez-nous au +${WHATSAPP_NUMBER}.`))};
 return <ScrollView style={[styles.container,{backgroundColor:colors.background}]} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
  <View style={styles.header}><View><Text style={[styles.kicker,{color:colors.textMuted}]}>MON ESPACE</Text><Text style={[styles.title,{color:colors.text}]}>Mon profil</Text></View><View style={[styles.avatarSmall,{backgroundColor:colors.primary+'18'}]}><MaterialCommunityIcons name="account-heart-outline" size={22} color={colors.primary}/></View></View>
  <View style={[styles.identity,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={[styles.avatar,{backgroundColor:colors.primary+'18'}]}><Text style={[styles.avatarLetter,{color:colors.primary}]}>{(parent.prenom||'P').charAt(0).toUpperCase()}</Text></View><View style={{flex:1}}><Text style={[styles.name,{color:colors.text}]}>{nom}</Text><Text style={[styles.email,{color:colors.textMuted}]}>{parent.email||'Compte parent'}</Text><Text style={[styles.role,{color:colors.primary}]}>Compte parent</Text></View></View>
  <Text style={[styles.section,{color:colors.text}]}>Mes enfants</Text>{loading?<ActivityIndicator color={colors.primary} style={{marginVertical:15}}/>:enfants.map(e=><TouchableOpacity key={e.uid} style={[styles.child,{backgroundColor:colors.surface,borderColor:colors.border}]} onPress={()=>navigation.navigate('ParentSuiviDetail',{enfant:e})}><View style={[styles.childIcon,{backgroundColor:colors.primary+'14'}]}><MaterialCommunityIcons name="account-child" size={23} color={colors.primary}/></View><View style={{flex:1}}><Text style={[styles.itemTitle,{color:colors.text}]}>{e.prenom}</Text><Text style={[styles.itemSub,{color:colors.textMuted}]}>{e.classe||'Classe non renseignée'}</Text></View><MaterialCommunityIcons name="chevron-right" size={21} color={colors.textMuted}/></TouchableOpacity>)}
  <TouchableOpacity style={[styles.primaryAction,{backgroundColor:colors.primary}]} onPress={()=>navigation.navigate('ParentLier')}><MaterialCommunityIcons name="account-plus-outline" size={21} color="#fff"/><Text style={styles.primaryText}>Ajouter un enfant</Text></TouchableOpacity>
  <Text style={[styles.section,{color:colors.text}]}>Choisir un accompagnement</Text>{PLANS.map(p=><View key={p.name} style={[styles.plan,{backgroundColor:colors.surface,borderColor:p.name==='GOLD'?colors.primary:colors.border}]}><View style={styles.planHead}><View><Text style={[styles.planName,{color:colors.text}]}>{p.name}</Text><Text style={[styles.itemSub,{color:colors.textMuted}]}>{p.desc}</Text></View><Text style={[styles.planPrice,{color:colors.primary}]}>{p.price}</Text></View>{p.features.map(f=><View key={f} style={styles.feature}><MaterialCommunityIcons name="check-circle" size={16} color={colors.primary}/><Text style={[styles.itemSub,{color:colors.text}]}>{f}</Text></View>)}<TouchableOpacity style={[styles.planButton,{backgroundColor:p.name==='GOLD'?colors.primary:colors.surface,borderColor:colors.primary}]} onPress={()=>choisirPlan(p)}><MaterialCommunityIcons name={p.name==='FREE'?'check-circle':'whatsapp'} size={17} color={p.name==='GOLD'?'#fff':colors.primary}/><Text style={[styles.planButtonText,{color:p.name==='GOLD'?'#fff':colors.primary}]}>{p.name==='FREE'?'Continuer gratuitement':`Activer ${p.name} via WhatsApp`}</Text></TouchableOpacity></View>)}
  <Text style={[styles.section,{color:colors.text}]}>Mon compte</Text><View style={[styles.menu,{backgroundColor:colors.surface,borderColor:colors.border}]}><InfoRow icon="account-outline" label="Informations personnelles" onPress={()=>navigation.navigate('ParentCompte',{mode:'personal'})} colors={colors}/><InfoRow icon="shield-lock-outline" label="Sécurité" onPress={()=>navigation.navigate('ParentCompte',{mode:'security'})} colors={colors}/><InfoRow icon="bell-outline" label="Notifications" onPress={()=>navigation.navigate('ParentCompte',{mode:'notifications'})} colors={colors}/><InfoRow icon="lifebuoy" label="Aide et support" onPress={()=>navigation.navigate('ParentSupport')} colors={colors} last/></View>
  <TouchableOpacity style={styles.logout} onPress={deconnecter}><MaterialCommunityIcons name="logout" size={20} color="#D32F2F"/><Text style={styles.logoutText}>Déconnexion</Text></TouchableOpacity>
 </ScrollView>}
function InfoRow({icon,label,onPress,colors,last}:any){return <TouchableOpacity onPress={onPress} style={[styles.menuRow,!last&&{borderBottomWidth:1,borderBottomColor:colors.border}]}><MaterialCommunityIcons name={icon} size={21} color={colors.primary}/><Text style={[styles.menuLabel,{color:colors.text}]}>{label}</Text><MaterialCommunityIcons name="chevron-right" size={20} color={colors.textMuted}/></TouchableOpacity>}
const styles=StyleSheet.create({container:{flex:1},content:{padding:18,paddingBottom:35},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:16},kicker:{fontSize:10,fontWeight:'800',letterSpacing:1.2},title:{fontSize:25,fontWeight:'900',marginTop:3},avatarSmall:{width:42,height:42,borderRadius:21,justifyContent:'center',alignItems:'center'},identity:{borderWidth:1,borderRadius:22,padding:17,flexDirection:'row',alignItems:'center',gap:13,marginBottom:20},avatar:{width:62,height:62,borderRadius:31,justifyContent:'center',alignItems:'center'},avatarLetter:{fontSize:25,fontWeight:'900'},name:{fontSize:19,fontWeight:'900'},email:{fontSize:11,marginTop:3},role:{fontSize:10,fontWeight:'800',marginTop:7},section:{fontSize:16,fontWeight:'900',marginBottom:9,marginTop:3},child:{borderWidth:1,borderRadius:18,padding:13,flexDirection:'row',alignItems:'center',gap:11,marginBottom:8},childIcon:{width:45,height:45,borderRadius:15,justifyContent:'center',alignItems:'center'},itemTitle:{fontSize:13,fontWeight:'900'},itemSub:{fontSize:11,lineHeight:16,marginTop:3},primaryAction:{minHeight:48,borderRadius:15,justifyContent:'center',alignItems:'center',flexDirection:'row',gap:8,marginBottom:20},primaryText:{color:'#fff',fontSize:13,fontWeight:'900'},plan:{borderWidth:1,borderRadius:20,padding:15,marginBottom:10},planHead:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between',gap:10},planName:{fontSize:17,fontWeight:'900'},planPrice:{fontSize:13,fontWeight:'900'},feature:{flexDirection:'row',alignItems:'center',gap:7,marginTop:9},planButton:{minHeight:42,borderWidth:1,borderRadius:13,justifyContent:'center',alignItems:'center',marginTop:12,flexDirection:'row',gap:7},planButtonText:{fontSize:12,fontWeight:'900'},menu:{borderWidth:1,borderRadius:18,paddingHorizontal:14,marginBottom:15},menuRow:{minHeight:54,flexDirection:'row',alignItems:'center',gap:12},menuLabel:{flex:1,fontSize:13,fontWeight:'700'},logout:{minHeight:52,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,marginTop:4},logoutText:{color:'#D32F2F',fontSize:14,fontWeight:'900'}});
