import React, { useCallback, useMemo, useRef, useState } from 'react';
import { View, Text, StyleSheet, ScrollView, ActivityIndicator } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useFocusEffect } from '@react-navigation/native';
import { useTheme } from '../../context/ThemeContext';
import { getEnfantsLies, getSessionsEnfant } from '../../services/parentService';

export default function ParentSuiviDetail({ route }: any) {
  const { colors } = useTheme();
  const [loading,setLoading]=useState(true);
  const [enfant,setEnfant]=useState<any>(route?.params?.enfant||null);
  const enfantRef=useRef<any>(route?.params?.enfant||null);
  const [sessions,setSessions]=useState<any[]>([]);
  const charger=useCallback(async()=>{
    setLoading(true);
    try{
      const enfants=await getEnfantsLies();
      const uid=enfantRef.current?.uid;
      const actif=(uid?enfants.find(e=>e.uid===uid):null)||enfants[0]||null;
      enfantRef.current=actif;
      setEnfant(actif);
      if(actif)setSessions(await getSessionsEnfant(actif.uid)); else setSessions([]);
    }catch(e){console.error('[ParentSuiviDetail] chargement:',e)}finally{setLoading(false)}
  },[]);
  useFocusEffect(useCallback(()=>{charger()},[charger]));
  const notes=sessions.map(s=>Number(s.note??s.score??(s.scoreTotal&&s.scoreMax?(s.scoreTotal/s.scoreMax)*20:NaN))).filter(n=>Number.isFinite(n)&&n>0);
  const moyenne=notes.length?notes.reduce((a,b)=>a+b,0)/notes.length:0;
  const matieres=useMemo(()=>{const map:Record<string,{points:number;count:number}>={};sessions.forEach(s=>{const m=s.matiere||'Autre';const n=Number(s.note??s.score??(s.scoreTotal&&s.scoreMax?(s.scoreTotal/s.scoreMax)*20:NaN));if(!map[m])map[m]={points:0,count:0};if(Number.isFinite(n)){map[m].points+=n;map[m].count++}});return Object.entries(map).map(([nom,v])=>({nom,note:v.count?v.points/v.count:0,count:v.count})).sort((a,b)=>b.note-a.note)},[sessions]);
  const recent=sessions.slice(0,6); const regularite=Math.min(100,Math.round((Math.min(sessions.length,5)/5)*100)); const focus=matieres.length?matieres[matieres.length-1].nom:'à construire';
  if(loading && !enfant && sessions.length===0)return <View style={[styles.center,{backgroundColor:colors.background}]}><ActivityIndicator color={colors.primary} size="large"/></View>;
  return <ScrollView style={[styles.container,{backgroundColor:colors.background}]} contentContainerStyle={styles.content}>
    <Text style={[styles.title,{color:colors.text}]}>Suivi détaillé</Text><Text style={[styles.subtitle,{color:colors.textMuted}]}>{enfant?.prenom||'Votre enfant'} · vision globale de la scolarité</Text>
    <View style={[styles.hero,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={styles.heroRow}><View style={[styles.heroIcon,{backgroundColor:colors.primary+'18'}]}><MaterialCommunityIcons name="school-outline" size={28} color={colors.primary}/></View><View style={{flex:1}}><Text style={[styles.heroLabel,{color:colors.textMuted}]}>INDICATEUR GLOBAL</Text><Text style={[styles.heroValue,{color:colors.text}]}>{moyenne?`${moyenne.toFixed(1)}/20`:'—'}</Text></View></View><Text style={[styles.heroText,{color:colors.textSecondary}]}>Une lecture consolidée des résultats et habitudes enregistrés dans RÉPETIA.</Text></View>
    <Text style={[styles.section,{color:colors.text}]}>Les 4 signaux utiles</Text><View style={styles.grid}><Metric icon="chart-line" label="Résultats" value={moyenne?`${moyenne.toFixed(1)}/20`:'—'} colors={colors}/><Metric icon="calendar-check" label="Régularité" value={`${regularite}%`} colors={colors}/><Metric icon="book-open-variant" label="Activités" value={String(sessions.length)} colors={colors}/><Metric icon="target" label="À renforcer" value={focus} colors={colors}/></View>
    <Text style={[styles.section,{color:colors.text}]}>Matières</Text>{matieres.length?<View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}>{matieres.map((m,i)=><View key={m.nom} style={[styles.subjectRow,i<matieres.length-1&&{borderBottomWidth:1,borderBottomColor:colors.border}]}><View style={{flex:1}}><Text style={[styles.subjectName,{color:colors.text}]}>{m.nom}</Text><Text style={[styles.subjectMeta,{color:colors.textMuted}]}>{m.count} activité(s)</Text></View><Text style={[styles.subjectNote,{color:m.note>=14?colors.success:m.note>=10?colors.warning:colors.error}]}>{m.note.toFixed(1)}/20</Text></View>)}</View>:<Empty text="Les résultats par matière apparaîtront après les premières activités." colors={colors}/>} 
    <Text style={[styles.section,{color:colors.text}]}>Habitudes de travail</Text><View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><Info icon="clock-outline" title="Régularité" text={sessions.length>=5?'Rythme suffisamment établi pour identifier des tendances.':'Encore quelques activités nécessaires pour mesurer une tendance fiable.'} colors={colors}/><Info icon="lightbulb-outline" title="Levier probable" text={focus==='à construire'?'Construire un historique régulier.':`Surveiller ${focus} et comparer les prochaines évaluations.`} colors={colors}/></View>
    <Text style={[styles.section,{color:colors.text}]}>Dernières activités</Text><View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}>{recent.length?recent.map((s,i)=><View key={s.id||i} style={[styles.activity,i<recent.length-1&&{borderBottomWidth:1,borderBottomColor:colors.border}]}><MaterialCommunityIcons name="check-circle-outline" size={20} color={colors.primary}/><View style={{flex:1}}><Text style={[styles.subjectName,{color:colors.text}]}>{s.matiere||s.titre||'Activité scolaire'}</Text><Text style={[styles.subjectMeta,{color:colors.textMuted}]}>{s.date?new Date(s.date).toLocaleDateString('fr-FR'):'Date non renseignée'}</Text></View><Text style={[styles.subjectNote,{color:colors.primary}]}>{s.score!=null?`${s.score}/20`:'—'}</Text></View>):<Text style={[styles.body,{color:colors.textMuted}]}>Aucune activité récente.</Text>}</View>
    <View style={[styles.aiCard,{backgroundColor:colors.primary}]}><MaterialCommunityIcons name="robot-outline" size={26} color="#fff"/><View style={{flex:1}}><Text style={styles.aiTitle}>Analyse intelligente</Text><Text style={styles.aiText}>Quand l’historique est suffisant, RÉPETIA peut comparer résultats, régularité et difficultés pour proposer les prochains leviers d’action.</Text></View></View>
  </ScrollView>;
}
function Metric({icon,label,value,colors}:any){return <View style={[styles.metric,{backgroundColor:colors.surface,borderColor:colors.border}]}><MaterialCommunityIcons name={icon} size={20} color={colors.primary}/><Text style={[styles.metricValue,{color:colors.text}]} numberOfLines={1}>{value}</Text><Text style={[styles.metricLabel,{color:colors.textMuted}]}>{label}</Text></View>}
function Info({icon,title,text,colors}:any){return <View style={styles.info}><MaterialCommunityIcons name={icon} size={20} color={colors.primary}/><View style={{flex:1}}><Text style={[styles.subjectName,{color:colors.text}]}>{title}</Text><Text style={[styles.body,{color:colors.textSecondary}]}>{text}</Text></View></View>}
function Empty({text,colors}:any){return <View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.body,{color:colors.textMuted}]}>{text}</Text></View>}
const styles=StyleSheet.create({container:{flex:1},content:{padding:16,paddingBottom:36},center:{flex:1,justifyContent:'center',alignItems:'center'},title:{fontSize:25,fontWeight:'900'},subtitle:{fontSize:12,marginTop:4,marginBottom:16},hero:{borderWidth:1,borderRadius:22,padding:18,marginBottom:18},heroRow:{flexDirection:'row',alignItems:'center',gap:12},heroIcon:{width:54,height:54,borderRadius:17,justifyContent:'center',alignItems:'center'},heroLabel:{fontSize:10,fontWeight:'800',letterSpacing:1},heroValue:{fontSize:27,fontWeight:'900',marginTop:2},heroText:{fontSize:12,lineHeight:18,marginTop:12},section:{fontSize:17,fontWeight:'900',marginTop:5,marginBottom:9},grid:{flexDirection:'row',flexWrap:'wrap',gap:9,marginBottom:13},metric:{width:'48%',minHeight:88,borderWidth:1,borderRadius:17,padding:13},metricValue:{fontSize:17,fontWeight:'900',marginTop:8},metricLabel:{fontSize:10,marginTop:2},card:{borderWidth:1,borderRadius:18,padding:14,marginBottom:13},subjectRow:{flexDirection:'row',alignItems:'center',paddingVertical:12},subjectName:{fontSize:13,fontWeight:'800'},subjectMeta:{fontSize:10,marginTop:2},subjectNote:{fontSize:14,fontWeight:'900'},body:{fontSize:12,lineHeight:18},info:{flexDirection:'row',gap:11,paddingVertical:8},activity:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:12},aiCard:{borderRadius:19,padding:16,flexDirection:'row',gap:12,marginTop:3},aiTitle:{color:'#fff',fontSize:14,fontWeight:'900'},aiText:{color:'rgba(255,255,255,.86)',fontSize:11,lineHeight:17,marginTop:4}});
