import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Alert, Linking } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useTheme } from '../../context/ThemeContext';
import { useAuth } from '../../context/AuthContext';
const WHATSAPP_NUMBER='24160217098';
const PLANS=[
{id:'gratuit',name:'FREE',price:'0 FCFA',tag:'Pour découvrir RÉPETIA',features:['Suivi essentiel','5 questions IA/jour','2 analyses document/semaine']},
{id:'gold',name:'GOLD',price:'5 000 FCFA/mois',tag:'Le meilleur équilibre',features:['IA étendue','Analyses de documents','Suivi de progression avancé','8 matières']},
{id:'platinum',name:'PLATINUM',price:'18 000 FCFA/mois',tag:'Accompagnement maximal',features:['Tout GOLD','Recommandations IA avancées','Priorité support','Fonctionnalités famille']}];
export default function AbonnementScreenV2(){const{colors}=useTheme();const{user}=useAuth();const choisir=(p:any)=>{if(p.id==='gratuit'){Alert.alert('Plan FREE','Le plan Free est actif sans paiement.');return}const message=`Bonjour ! Je souhaite activer le plan ${p.name} de RÉPETIA.\n\nPlan : ${p.name}\nPrix : ${p.price}\nEmail : ${user?.email||'non renseigné'}\n\nJe souhaite connaître la procédure de paiement et d’activation.`;Linking.openURL(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`).catch(()=>Alert.alert('WhatsApp indisponible',`Contactez-nous au +${WHATSAPP_NUMBER}.`))};return <ScrollView style={[styles.container,{backgroundColor:colors.background}]} contentContainerStyle={styles.content}><Text style={[styles.title,{color:colors.text}]}>Abonnement RÉPETIA</Text><Text style={[styles.sub,{color:colors.textMuted}]}>Choisis ton plan. Pour les plans payants, la demande d’activation s’ouvre directement dans WhatsApp avec ton plan prérempli.</Text>{PLANS.map(p=><View key={p.id} style={[styles.card,{backgroundColor:colors.surface,borderColor:p.id==='gold'?colors.primary:colors.border}]}>{p.id==='gold'&&<View style={[styles.badge,{backgroundColor:colors.primary}]}><Text style={styles.badgeText}>⭐ POPULAIRE</Text></View>}<Text style={[styles.name,{color:colors.text}]}>{p.name}</Text><Text style={[styles.price,{color:colors.primary}]}>{p.price}</Text><Text style={[styles.tag,{color:colors.textMuted}]}>{p.tag}</Text>{p.features.map((f:string)=><View key={f} style={styles.feature}><MaterialCommunityIcons name="check-circle" size={17} color={colors.primary}/><Text style={[styles.featureText,{color:colors.text}]}>{f}</Text></View>)}<TouchableOpacity onPress={()=>choisir(p)} style={[styles.button,{backgroundColor:p.id==='gold'?colors.primary:colors.background,borderColor:colors.border}]}><MaterialCommunityIcons name={p.id==='gratuit'?'check-circle':'whatsapp'} size={18} color={p.id==='gold'?'#fff':colors.primary}/><Text style={{color:p.id==='gold'?'#fff':colors.primary,fontWeight:'900'}}>{p.id==='gratuit'?'Continuer gratuitement':'Activer via WhatsApp'}</Text></TouchableOpacity></View>)}</ScrollView>};
const styles=StyleSheet.create({container:{flex:1},content:{padding:18,paddingBottom:35},title:{fontSize:25,fontWeight:'900'},sub:{fontSize:12,lineHeight:18,marginTop:5,marginBottom:16},card:{borderWidth:1,borderRadius:20,padding:16,marginBottom:12},badge:{alignSelf:'flex-start',borderRadius:12,paddingHorizontal:9,paddingVertical:5,marginBottom:10},badgeText:{color:'#fff',fontSize:9,fontWeight:'900'},name:{fontSize:18,fontWeight:'900'},price:{fontSize:18,fontWeight:'900',marginTop:5},tag:{fontSize:11,marginTop:3,marginBottom:11},feature:{flexDirection:'row',alignItems:'center',gap:7,marginTop:8},featureText:{fontSize:12,fontWeight:'700'},button:{minHeight:46,borderWidth:1,borderRadius:14,justifyContent:'center',alignItems:'center',marginTop:14,flexDirection:'row',gap:8}});
