import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView, TextInput, Alert, ActivityIndicator, Linking, Image } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useTheme } from '../../context/ThemeContext';
import { useAuth } from '../../context/AuthContext';
import { AGENTS } from '../../services/iaServiceOpenRouter';
import { getTuteur, getAvisTuteur, creerReservation, Tuteur, Avis } from '../../services/tuteurService';
import { db, auth } from '../../services/firebaseConfig';
import { collection, getDocs, query, where } from 'firebase/firestore';

type Onglet='profil'|'reserver'|'avis';
export default function TuteurProfilScreen({ route, navigation }: any) {
  const { colors }=useTheme(); const { userData }=useAuth(); const { tuteurId,tuteur:tParam }=route.params||{};
  const [tuteur,setTuteur]=useState<Tuteur|null>(tParam||null); const [avis,setAvis]=useState<Avis[]>([]); const [cours,setCours]=useState(0); const [loading,setLoading]=useState(!tParam); const [onglet,setOnglet]=useState<Onglet>('profil');
  const [duree,setDuree]=useState(30); const [date,setDate]=useState(''); const [heure,setHeure]=useState(''); const [matiere,setMatiere]=useState(''); const [message,setMessage]=useState(''); const [saving,setSaving]=useState(false);
  useEffect(()=>{(async()=>{try{const t=tParam||await getTuteur(tuteurId);setTuteur(t);if(tuteurId){const [a,c]=await Promise.all([getAvisTuteur(tuteurId),getDocs(query(collection(db,'contributions'),where('auteur.userId','==',tuteurId),where('statut','==','validé')))]);setAvis(a);setCours(c.size);}if(t?.matieres?.[0])setMatiere(t.matieres[0]);}catch(e){console.error(e);}finally{setLoading(false);}})();},[tuteurId]);
  if(loading)return <View style={[styles.center,{backgroundColor:colors.background}]}><ActivityIndicator size="large" color={colors.primary}/></View>;
  if(!tuteur)return <View style={[styles.center,{backgroundColor:colors.background}]}><Text style={{color:colors.text}}>Répétiteur introuvable</Text><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={{color:colors.primary,marginTop:10}}>Retour</Text></TouchableOpacity></View>;
  const accent=AGENTS.find(a=>a.matiere===tuteur.matieres?.[0])?.couleur||colors.primary;
  const reserver=async()=>{if(!date||!heure)return Alert.alert('Infos manquantes','Indiquez une date et une heure.');setSaving(true);try{const prix=duree===30?tuteur.prix30min:tuteur.prix60min;await creerReservation({eleveId:auth.currentUser?.uid||'',elevePrénom:(userData as any)?.prenom||'Élève',tuteurId:tuteur.uid,tuteurNom:`${tuteur.prenom} ${tuteur.nom}`,matiere,dureeMin:duree,prix,date,heure,message:message||'Session de révision'});const phone=tuteur.whatsapp||tuteur.telephone||'';if(phone)await Linking.openURL(`https://wa.me/${phone.replace(/\D/g,'')}?text=${encodeURIComponent(`Bonjour ${tuteur.prenom}, je souhaite réserver une session via RÉPÉTIA le ${date} à ${heure}.`)}`);Alert.alert('Demande envoyée','Votre demande a été enregistrée.');}catch(e){console.error(e);Alert.alert('Erreur','Impossible d’envoyer la demande.');}finally{setSaving(false);}};
  return <View style={[styles.container,{backgroundColor:colors.background}]}><LinearGradient colors={[accent,colors.surface]} style={styles.hero}><TouchableOpacity onPress={()=>navigation.goBack()} style={styles.back}><MaterialCommunityIcons name="arrow-left" size={24} color="white"/></TouchableOpacity><View style={[styles.avatar,{borderColor:'rgba(255,255,255,.5)'}]}>{tuteur.profileImage?<Image source={{uri:tuteur.profileImage}} style={styles.avatarImage}/>:<Text style={styles.avatarText}>👨🏾‍🏫</Text>}</View><Text style={styles.name}>{tuteur.prenom} {tuteur.nom}</Text>{tuteur.statut==='certifie'&&<View style={styles.certified}><MaterialCommunityIcons name="check-decagram" size={16} color="white"/><Text style={styles.certifiedText}>Certifié RÉPÉTIA</Text></View>}<View style={styles.rating}><MaterialCommunityIcons name="star" size={16} color="#FFD54F"/><Text style={styles.ratingText}>{Number(tuteur.noteGlobale||0).toFixed(1)} · {tuteur.nbAvis||0} avis</Text></View></LinearGradient>
  <View style={[styles.tabs,{backgroundColor:colors.surface,borderBottomColor:colors.border}]}>{(['profil','reserver','avis'] as Onglet[]).map(x=><TouchableOpacity key={x} onPress={()=>setOnglet(x)} style={[styles.tab,x===onglet&&{borderBottomColor:accent,borderBottomWidth:3}]}><Text style={{color:x===onglet?accent:colors.textMuted,fontWeight:'800',fontSize:12}}>{x==='profil'?'Profil':x==='reserver'?'Réserver':`Avis (${avis.length})`}</Text></TouchableOpacity>)}</View>
  <ScrollView contentContainerStyle={styles.content}>{onglet==='profil'&&<><View style={[styles.stats,{backgroundColor:colors.surface,borderColor:colors.border}]}>{[[cours,'Cours en ligne'],[tuteur.nbSessions||0,'Sessions'],[tuteur.nbAvis||0,'Avis'],[tuteur.anneeExp||0,'Ans exp.']].map(([v,l])=><View key={String(l)} style={styles.stat}><Text style={[styles.statValue,{color:accent}]}>{v}</Text><Text style={[styles.statLabel,{color:colors.textMuted}]}>{l}</Text></View>)}</View><View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.cardTitle,{color:colors.text}]}>Présentation</Text><Text style={[styles.body,{color:colors.textSecondary}]}>{tuteur.bio||'Ce répétiteur n’a pas encore ajouté de présentation.'}</Text></View><View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.cardTitle,{color:colors.text}]}>Matières</Text><View style={styles.wrap}>{(tuteur.matieres||[]).map(m=><View key={m} style={[styles.chip,{backgroundColor:accent+'15'}]}><Text style={{color:accent,fontWeight:'700',fontSize:12}}>{m}</Text></View>)}</View></View><View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.cardTitle,{color:colors.text}]}>Formation & expérience</Text><Text style={[styles.body,{color:colors.textSecondary}]}>🎓 {tuteur.diplome||'Formation non renseignée'}</Text><Text style={[styles.body,{color:colors.textSecondary,marginTop:7}]}>🏫 {tuteur.universite||'Université non renseignée'}</Text><Text style={[styles.body,{color:colors.textSecondary,marginTop:7}]}>⏱️ {tuteur.anneeExp||0} an(s) d’expérience</Text></View><TouchableOpacity onPress={()=>setOnglet('reserver')} style={[styles.cta,{backgroundColor:accent}]}><MaterialCommunityIcons name="calendar-plus" size={21} color="white"/><Text style={styles.ctaText}>Réserver une session</Text></TouchableOpacity></>}
  {onglet==='reserver'&&<View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.cardTitle,{color:colors.text}]}>Réserver avec {tuteur.prenom}</Text><Text style={[styles.label,{color:colors.text}]}>Matière</Text><View style={styles.wrap}>{(tuteur.matieres||[]).map(m=><TouchableOpacity key={m} onPress={()=>setMatiere(m)} style={[styles.chip,{backgroundColor:m===matiere?accent+'20':colors.background,borderColor:m===matiere?accent:colors.border,borderWidth:1}]}><Text style={{color:m===matiere?accent:colors.text,fontWeight:'700',fontSize:12}}>{m}</Text></TouchableOpacity>)}</View><Text style={[styles.label,{color:colors.text}]}>Durée</Text><View style={styles.wrap}><TouchableOpacity onPress={()=>setDuree(30)} style={[styles.duration,{backgroundColor:duree===30?accent+'18':colors.background,borderColor:duree===30?accent:colors.border}]}><Text style={{color:colors.text,fontWeight:'700'}}>30 min · {Number(tuteur.prix30min||0).toLocaleString()} FCFA</Text></TouchableOpacity><TouchableOpacity onPress={()=>setDuree(60)} style={[styles.duration,{backgroundColor:duree===60?accent+'18':colors.background,borderColor:duree===60?accent:colors.border}]}><Text style={{color:colors.text,fontWeight:'700'}}>60 min · {Number(tuteur.prix60min||0).toLocaleString()} FCFA</Text></TouchableOpacity></View><Text style={[styles.label,{color:colors.text}]}>Date</Text><TextInput value={date} onChangeText={setDate} placeholder="2026-09-01" placeholderTextColor={colors.textMuted} style={[styles.input,{backgroundColor:colors.background,borderColor:colors.border,color:colors.text}]}/><Text style={[styles.label,{color:colors.text}]}>Heure</Text><TextInput value={heure} onChangeText={setHeure} placeholder="16:00" placeholderTextColor={colors.textMuted} style={[styles.input,{backgroundColor:colors.background,borderColor:colors.border,color:colors.text}]}/><Text style={[styles.label,{color:colors.text}]}>Message</Text><TextInput value={message} onChangeText={setMessage} multiline placeholder="Un mot pour le répétiteur..." placeholderTextColor={colors.textMuted} style={[styles.input,{height:80,textAlignVertical:'top',backgroundColor:colors.background,borderColor:colors.border,color:colors.text}]}/><TouchableOpacity disabled={saving} onPress={reserver} style={[styles.cta,{backgroundColor:accent,opacity:saving?.55:1}]}>{saving?<ActivityIndicator color="white"/>:<><MaterialCommunityIcons name="send" size={20} color="white"/><Text style={styles.ctaText}>Envoyer la demande</Text></>}</TouchableOpacity></View>}
  {onglet==='avis'&&(avis.length?avis.map(a=><View key={a.id} style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.body,{color:colors.text}]}>{a.elevePrénom||'Élève'} · ⭐ {a.note}/5</Text><Text style={[styles.body,{color:colors.textSecondary,marginTop:5}]}>{a.commentaire}</Text></View>):<Text style={[styles.empty,{color:colors.textMuted}]}>Aucun avis pour le moment.</Text>)}</ScrollView></View>;
}
const styles=StyleSheet.create({container:{flex:1},hero:{paddingTop:18,paddingBottom:16,alignItems:'center'},back:{position:'absolute',left:12,top:14,width:40,height:40,alignItems:'center',justifyContent:'center'},avatar:{width:72,height:72,borderRadius:36,borderWidth:2,alignItems:'center',justifyContent:'center',overflow:'hidden'},avatarImage:{width:'100%',height:'100%'},avatarText:{fontSize:36},name:{color:'white',fontSize:22,fontWeight:'900',marginTop:8},certified:{flexDirection:'row',alignItems:'center',gap:5,marginTop:5},certifiedText:{color:'white',fontSize:11,fontWeight:'800'},rating:{flexDirection:'row',alignItems:'center',gap:5,marginTop:6},ratingText:{color:'white',fontSize:12,fontWeight:'700'},tabs:{flexDirection:'row',borderBottomWidth:1},tab:{flex:1,alignItems:'center',paddingVertical:12},content:{padding:15,paddingBottom:35},stats:{flexDirection:'row',borderWidth:1,borderRadius:17,paddingVertical:15,marginBottom:12},stat:{flex:1,alignItems:'center'},statValue:{fontSize:19,fontWeight:'900'},statLabel:{fontSize:9,marginTop:3},card:{borderWidth:1,borderRadius:17,padding:15,marginBottom:12},cardTitle:{fontSize:16,fontWeight:'900',marginBottom:10},body:{fontSize:13,lineHeight:19},wrap:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{paddingHorizontal:10,paddingVertical:8,borderRadius:12},label:{fontSize:12,fontWeight:'800',marginTop:10,marginBottom:6},duration:{borderWidth:1,borderRadius:12,padding:11,marginBottom:7},input:{minHeight:46,borderWidth:1,borderRadius:12,paddingHorizontal:12,fontSize:14},cta:{minHeight:50,borderRadius:14,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,marginTop:8},ctaText:{color:'white',fontSize:15,fontWeight:'900'},empty:{textAlign:'center',marginTop:40},center:{flex:1,alignItems:'center',justifyContent:'center'}});
